### PR TITLE
Problem Graph

### PR DESCRIPTION
**Pull request by Elscrux**
Reworked solver configuration with graph based approach.

### CODE REVIEW

**Comment by koalamitice** [comment]
Some issues that occured while testing the frontend:

- In the MaxCut solver, after selecting Cirq Maxcut, "Solving" is not shown after clicking "solve".
- When using the Qiskit MaxCut solver, the GML parsing fails
- Opening a Problem Mask sites after clicking on it takes unusually long

**Review by koalamitice — CHANGES_REQUESTED** [review]
The following things need to be fixed:

- In the MaxCut solver, after selecting Cirq Maxcut, "Solving" is not shown after clicking "solve".
- When using the Qiskit MaxCut solver, the GML parsing fails
- Opening a Problem Mask site after clicking on it takes unusually long (this could be a problem of dynamic compiling, maybe this is not an actual issue)
- Selecting a Solver for a node with multiple subproblems, while the sub-problem list is extended does not refresh the selected solver in the list of problems. (Still shows "-", even though a solver was selected). Is fixed when list is closed and expanded again.
See video:

https://github.com/user-attachments/assets/4b0f6fd3-6c3e-477f-85f8-d7460fec395b


- When a Problem is solved and the nodes are moved around afterwards they seem to have some weird jumping behavior (they move a little bit)
See video:

https://github.com/user-attachments/assets/6744ab5f-b675-4dcf-a311-544c6cd745db

- The QUBO solver does not auto-resize at when selecting "configure solver" (nodes are too big)
- The QUBO solver does not show "Solving" when starting the solving process.
- All solvers show "Solution by null" in the solution Data. (should be the solver name)
- The Solver: entry in the Meta Data is always null (probably same issues as solution by null)

**Comment by Elscrux** [comment]
> In the MaxCut solver, after selecting Cirq Maxcut, "Solving" is not shown after clicking "solve".

> The QUBO solver does not show "Solving" when starting the solving process.

This is solved now

**Comment by Elscrux** [comment]
> When using the Qiskit MaxCut solver, the GML parsing fails

@koalamitice For me it works with the 3-nodes-3-edges example in the backend. Can you please tell me which setup you have and what the exact error is?

**Comment by Elscrux** [comment]
> Opening a Problem Mask site after clicking on it takes unusually long (this could be a problem of dynamic compiling, maybe this is not an actual issue)

I noticed this too, but when trying out a built version of the website there is no delay at all, so I assume you're right.

**Comment by Elscrux** [comment]
> Selecting a Solver for a node with multiple subproblems, while the sub-problem list is extended does not refresh the selected solver in the list of problems. (Still shows "-", even though a solver was selected). Is fixed when list is closed and expanded again.

Should be fixed now

**Comment by Elscrux** [comment]
> When a Problem is solved and the nodes are moved around afterwards they seem to have some weird jumping behavior (they move a little bit)

This should be fixed now too

**Comment by Elscrux** [comment]
> The QUBO solver does not auto-resize at when selecting "configure solver" (nodes are too big)

I'm not sure what you mean, could you send a screenshot?

**Comment by Elscrux** [comment]
> All solvers show "Solution by null" in the solution Data. (should be the solver name)
The Solver: entry in the Meta Data is always null (probably same issues as solution by null)

This seems to be a backend issue. I'll fix it on [#78](https://github.com/ProvideQ/toolbox-server/pull/78)

**Comment by koalamitice** [comment]
@Elscrux the VRP problem mask nearly works now. There is still an issue that the Solution is not shown in the Solution Tab. Everything else seems to work fine. 

Screenshot of the problem: (No Solution shown, even though problem was solved successfully)
Bildschirmfoto 2024-09-04 um 14 39 15

**Comment by Elscrux** [comment]
> @Elscrux the VRP problem mask nearly works now. There is still an issue that the Solution is not shown in the Solution Tab. Everything else seems to work fine.
> 
> Screenshot of the problem: (No Solution shown, even though problem was solved successfully) Bildschirmfoto 2024-09-04 um 14 39 15

Might be a backend issue. Could you confirm with the debugger or so that the solution is properly set?

**Comment by koalamitice** [comment]
> > @Elscrux the VRP problem mask nearly works now. There is still an issue that the Solution is not shown in the Solution Tab. Everything else seems to work fine.
> > Screenshot of the problem: (No Solution shown, even though problem was solved successfully) Bildschirmfoto 2024-09-04 um 14 39 15
> 
> Might be a backend issue. Could you confirm with the debugger or so that the solution is properly set?

Thanks for the input, was actually a backend issue. The clusterers did not set any solutionData. Fixed with: https://github.com/ProvideQ/toolbox-server/pull/86

**Review by koalamitice — APPROVED** [review]
Tested Changes locally, everything looks good now!

**Pull request merged**
